export {Login} from  "./Login"
export {Register} from "./Register"
export {Perfil} from "./Perfil"
export {Mensagem} from "./Mensagem"
export {CadMessage} from "./CadMensagem"
export { QrCode as QrCode} from"./QrCode"
export { LocationMap as LocationMap} from "./LocationMap"
export { Acelerometro as Acelerometro } from "./Acelerometro"